# Generated by Django 4.0.5 on 2022-10-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('Enquiry', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
